dlang-community/awesome-d

- README.md
Hi,
I'm the author of TinyRedis, a Redis (redis.io) driver written in pure D. I've added a link to my package. TinyRedis is a stable package and has been in development for a few years. It's fast and simple for new users, and has no dependencies. 
A pull is appreciated!
Thanks,
Adil
> Added Tiny Redis

- README.md
Mir is now an own organization ;-)
> add link to the libmir organization

- README.md
afaik @adamdruppe's this week in D is the only blog that is actively maintained, so I put it in front ;-)
> add blog this week in D

- README.md
> better description for mir

- README.md
Ping @atilaneves and @nomad-software
> add section about testing frameworks

- README.md
I didn't know where exactly to add?
> add d functional garden

- README.md
@atilaneves you probably know more?
> add build tools

- README.md
An update to tsv utilities entries. Should read a bit better now.
> Tsv utils update

- README.md
> Add new OS

- README.md
> Fix DDT URL

- README.md
I was hoping to have these packages added to the list, thanks!
~k
> Adding entries for apache-thrift and d-language-server.

- README.md
Add [Luneta](https://github.com/fbeline/luneta) in the Command line section.
> Add luneta

- README.md
The original author of Dexed has started working on it again, so this PR adjusts the link to their new Gitlab repo for it.
> Update Dexed link again

- README.md
A link to my backgammony game written with GtkD and Dlang.
> Add Backgammony

- README.md
> add Tasty D Blog, fix #83

- README.md
development on dls has stopped, project was archived
> replace dls with serve-d

- README.md
currently unmaintained, fix #98
> remove Diamond MVC

- README.md
> add BindBC libraries

- README.md
Admittedly it is my own library. But I find it pretty awesome!
> Add Poodinis dependency injection to list

- README.md
I added the D discord server, a vey active D community.
> Added D Discord Server

- README.md
> Deleted Link

- README.md
Deleted the branch the first time, so I did it again.
> Added Godot-D (again)

- README.md
Added new subsection for wip compilers like sdc. Modify it as you see fit.
> Deleted dil compiler and added new subsection.

- README.md
Add a command line utility written in Dlang.
It records all cryptic commands and acronyms' meanings, for example:
```bash
$ cr dmd
$ Digital Mars D compiler
$ cr ucfs 
$ Uniform Function Call Syntax in Dlang
$ cr rxvt
$ Rob's xvt(X Virtual Terminal) or our extended virtual terminal
```
> Add Cryptic_Resolver

- README.md
In development, robust solution for rigging virtual puppets (think vtubers). 
Powerful software written in Dlang, only one of its kind.
> add Inochi creator

- README.md
> Added dlog, gogga, libpb, jstruct

- README.md
> add grain2 & tfd

- README.md
New apps written in D:
* Onedrive - Linux Client for Microsoft Drive.
* Literate - A Literate programming tool.
> Add new end-user apps

- README.md
* Removed [stomp](https://github.com/huntlabs/hunt-stomp) and [darg](https://github.com/jasonwhite/darg).
* Moved recently updated projects up.
* Added some games and GUI libraries.
* Created a GUI Apps section and tilix was moved there.
> Removed 2 libraries, moved things and added GUI and game stuff.

- README.md
I did not remove anything this time :)
Just added some basic libraries and moved old projects down.
> Added numem, joka, inmath and moved old libraries down.

- README.md
Only added and moved things. Nothing was removed.
I also changed the description of BindBC a little bit.
> New GUI apps, sokol-d and moved some bindings up.

- README.md
I rewrote and moved stuff around in the game sections. Also, I found a dead link in the game sections, so I removed the item that had this link from the list. This was the item:
```md
[bindbc-assimp](https://github.com/Sobaya007/bindbc-assimp)
```
Note: Items that were similar between Derelict and BindBC have been removed from Derelict to encourage more users to use the BindBC bindings.
> Cleaned game sections.

- README.md
> Fixed a link and removed a dead link.
